# Generated by Django 4.2.5 on 2023-10-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_options_fooditem_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(error_messages={'unique': 'Category name already exist.'}, max_length=50, unique=True),
        ),
    ]
